name: Latest Windows

on: [push, pull_request]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - name: сheckout
      uses: actions/checkout@main

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@master

    - name: msbuild .
      run: msbuild . /m /p:configuration=${{matrix.configuration}}

    - name: artifacts
      uses: actions/upload-artifact@main
      with:
        name: package
        path: MPL/bin/
